name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      environment-variables: |
        BUILD_CONFIG=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
        VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}
      number-of-agents: 3
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
        pnpm exec nx-cloud record -- pnpm exec nx format:check
        pnpm exec nx affected --target=build --configuration=$BUILD_CONFIG --parallel=3
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      final-commands: |
        pnpm exec nx affected --target=deploy --configuration=$BUILD_CONFIG --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      environment-variables: |
        BUILD_CONFIG=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
        VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}
      number-of-agents: 3
